name = "clippy-edge"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "clippy-storage"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[durable_objects.bindings]]
name = "STREAM_PROCESSOR"
class_name = "StreamProcessor"

[[migrations]]
tag = "v1"
new_classes = ["StreamProcessor"]

[env.development]
vars = { ENVIRONMENT = "development" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
